Repository waifu-motivator/waifu-motivator-plugin, pull requests merged in 2020-09, with the labels that each got.

#185 feat: Frustration Events
  src/main/java/zd/zero/waifu/motivator/plugin/WaifuOfTheDayStartupActivity.java
  src/main/java/zd/zero/waifu/motivator/plugin/assets/VisualMotivationAssetProvider.kt
  src/main/java/zd/zero/waifu/motivator/plugin/listeners/IdleEventListener.kt
  src/main/java/zd/zero/waifu/motivator/plugin/listeners/TaskListener.kt
  src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterListenerImpl.kt
  src/main/java/zd/zero/waifu/motivator/plugin/motivation/event/MotivationEvent.kt
  src/main/java/zd/zero/waifu/motivator/plugin/motivation/event/MotivationEventCategory.kt
  src/main/java/zd/zero/waifu/motivator/plugin/motivation/event/MotivationEventListener.kt
  src/main/java/zd/zero/waifu/motivator/plugin/motivation/event/MotivationEvents.kt
  src/main/java/zd/zero/waifu/motivator/plugin/personality/Wendi.kt
  src/main/java/zd/zero/waifu/motivator/plugin/personality/core/IdlePersonalityCore.kt
  src/main/java/zd/zero/waifu/motivator/plugin/personality/core/PersonalityCore.kt
  src/main/java/zd/zero/waifu/motivator/plugin/personality/core/TaskPersonalityCore.kt
  src/main/java/zd/zero/waifu/motivator/plugin/personality/core/emotions/EmotionCore.kt
  src/main/java/zd/zero/waifu/motivator/plugin/personality/core/emotions/EmotionDerivationUnit.kt
  src/main/java/zd/zero/waifu/motivator/plugin/personality/core/emotions/EmotionalState.kt
  src/main/java/zd/zero/waifu/motivator/plugin/personality/core/emotions/NegativeEmotionDerivationUnit.kt
  src/main/java/zd/zero/waifu/motivator/plugin/personality/core/emotions/NeutralEmotionDerivationUnit.kt
  src/main/java/zd/zero/waifu/motivator/plugin/personality/core/emotions/PositiveEmotionDerivationUnit.kt
  src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorSettingsPage.form
  src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorSettingsPage.java
  src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorState.kt
  src/main/java/zd/zero/waifu/motivator/plugin/tools/Extensions.kt
  src/main/java/zd/zero/waifu/motivator/plugin/tools/ProbabilityTools.kt
  src/main/resources/messages/MessageBundle.properties
  src/test/java/zd/zero/waifu/motivator/plugin/personality/NegativeEmotionCoreTests.kt
  src/test/java/zd/zero/waifu/motivator/plugin/personality/PositiveEmotionCoreTests.kt
Labels: feature

#187 fix: only show task events on correct project
  src/main/java/zd/zero/waifu/motivator/plugin/listeners/TaskListener.kt
Labels: bug

#188 fix: able to close project before project is initalized
  src/main/java/zd/zero/waifu/motivator/plugin/WaifuMotivatorProject.java
Labels: bug

#196 fix: added manual asset list sync
  src/main/java/zd/zero/waifu/motivator/plugin/actions/AssetSyncAction.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetManager.kt
  src/main/java/zd/zero/waifu/motivator/plugin/onboarding/UserOnboarding.kt
  src/main/java/zd/zero/waifu/motivator/plugin/platform/LifeCycleManager.kt
  src/main/java/zd/zero/waifu/motivator/plugin/platform/UpdateAssetsListener.kt
  src/main/java/zd/zero/waifu/motivator/plugin/platform/UpdateListener.kt
  src/main/resources/META-INF/plugin.xml
  src/test/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetManagerTest.kt
Labels: type: enhancement

#195 fix: allow customization of allowed exit codes.
  src/main/java/zd/zero/waifu/motivator/plugin/listeners/ExitCodeListener.kt
  src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorSettingsPage.form
  src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorSettingsPage.java
  src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorState.kt
  src/main/resources/messages/MessageBundle.properties
Labels: type: enhancement

#189 chore: automatic deployment
  .editorconfig
  .github/workflows/dev-release.yml
  .github/workflows/pre-merge.yml
  .github/workflows/release.yml
  build.gradle
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/BuildTools.kt
  buildSrc/src/main/kotlin/CopyPluginDescription.kt
  buildSrc/src/main/kotlin/CreateReleaseNotes.kt
  buildSrc/src/main/kotlin/waifu-motivator-build-plugin.gradle.kts
  ciScripts/buildPlugin.sh
  gradle.properties
Labels: status: review-in-progress, type: chore

#200 bug: enable plugin to work without IDE restart
  src/main/java/zd/zero/waifu/motivator/plugin/WaifuMotivatorProject.java
  src/main/java/zd/zero/waifu/motivator/plugin/listeners/PluginInstallListener.kt
  src/main/resources/META-INF/plugin.xml
Labels: type: bug

#205 chore: fix memory leak and added exit code debug log
  src/main/java/zd/zero/waifu/motivator/plugin/listeners/ExitCodeListener.kt
  src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorSettingsPage.java
Labels: type: chore

#208 Bumping GitHub Action to latest version
  .github/workflows/pre-merge.yml
Labels: type: chore

#210 fix: use laf colors for Waifu of the Day dialog
  .github/workflows/pre-merge.yml
  src/main/java/zd/zero/waifu/motivator/plugin/alert/dialog/WaifuOfTheDayDialog.java
  src/main/resources/waifu_of_the_day/darcula_style.css
  src/main/resources/waifu_of_the_day/style.css
Labels: type: enhancement

#212 chore: 2020.3 build support
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/zd/zero/waifu/motivator/plugin/integrations/ErrorReporter.kt
Labels: type: chore

#215 WMP-206 Support: Added remote asset testing
  src/main/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetManager.kt
  src/test/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetManagerTest.kt
Labels: status: on-hold

#213 fix: ui freezing on visual notifications
  src/main/java/zd/zero/waifu/motivator/plugin/actions/MotivateMeAction.java
  src/main/java/zd/zero/waifu/motivator/plugin/assets/AssetManager.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetDefinitionService.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetManager.kt
  src/main/java/zd/zero/waifu/motivator/plugin/tools/AssetTools.kt
  src/test/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetDefinitionServiceTest.kt
  src/test/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetManagerTest.kt
Labels: status: feedback-provided, type: bug
