Repository waifu-motivator/waifu-motivator-plugin, pull requests merged in 2020-08, with the labels that each got.

#131 chore: Added error reporter
  build.gradle
  src/main/java/zd/zero/waifu/motivator/plugin/integrations/ErrorReporter.kt
  src/main/java/zd/zero/waifu/motivator/plugin/onboarding/UserOnboarding.kt
  src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorState.kt
  src/main/resources/META-INF/plugin.xml
Labels: chore

#137 fix: enable re-hydration of local asset checks on startup
  src/main/java/zd/zero/waifu/motivator/plugin/assets/LocalAssetService.kt
Labels: bug

#138 feat: visual motivation conversion
  src/main/java/zd/zero/waifu/motivator/plugin/WaifuMotivatorProject.java
  src/main/java/zd/zero/waifu/motivator/plugin/assets/AssetDefinitionService.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/AudibleAssetDefinitionService.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/TextAssetDefinitionService.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/VisualAssetDefinitionService.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/VisualMotivationAssetProvider.kt
  src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterListenerImpl.java
  src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterListenerImpl.kt
Labels: enhancement, feature

#143 fix: create notification group once
  src/main/java/zd/zero/waifu/motivator/plugin/alert/BaseWaifuNotification.kt
Labels: bug

#147 fix: redundant title description
  docs/CHANGELOG.md
Labels: bug

#148 fix: optimized plugin icon
  src/main/resources/META-INF/pluginIcon.svg
  src/main/resources/icons/wmp.svg
Labels: enhancement

#166 fix: decoupling audio assets from plugin bundle
  .idea/codeStyles/Project.xml
  src/main/java/zd/zero/waifu/motivator/plugin/WaifuMotivator.java
  src/main/java/zd/zero/waifu/motivator/plugin/WaifuMotivatorProject.java
  src/main/java/zd/zero/waifu/motivator/plugin/actions/MotivateMeAction.java
  src/main/java/zd/zero/waifu/motivator/plugin/alert/AlertAssetProvider.java
  src/main/java/zd/zero/waifu/motivator/plugin/alert/TextualWaifuNotification.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/AssetManager.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/AssetModels.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/AudibleAssetDefinitionService.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/AudibleAssetManager.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/MotivationAsset.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetDefinitionService.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetManager.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/TextAssetDefinitionService.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/VisualAssetDefinitionService.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/VisualAssetManager.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/VisualMotivationAssetProvider.kt
  src/main/java/zd/zero/waifu/motivator/plugin/motivation/TextualMotivationFactory.java
  src/main/java/zd/zero/waifu/motivator/plugin/motivation/VisualMotivationFactory.kt
  src/main/java/zd/zero/waifu/motivator/plugin/player/DefaultWaifuSoundPlayer.java
  src/main/java/zd/zero/waifu/motivator/plugin/player/EmptyWaifuSoundPlayer.java
  src/main/java/zd/zero/waifu/motivator/plugin/player/Mp3WaifuSoundPlayer.java
  src/main/java/zd/zero/waifu/motivator/plugin/player/WaifuSoundPlayerFactory.java
  src/main/java/zd/zero/waifu/motivator/plugin/tools/WaifuMotivatorAlertAssetCategoryDeserializer.kt
  src/main/resources/sound/ara_ara_sayonara.wav
  src/main/resources/sound/ganbatte_onii_chan.wav
  src/main/resources/sound/good_job.wav
  src/main/resources/sound/megumin_explosion.wav
  src/main/resources/sound/nice_nice_nice_nice.wav
  src/main/resources/sound/nico_nico_nii.wav
  src/main/resources/sound/nyaan.mp3
  src/main/resources/sound/ohmygah.mp3
  src/main/resources/sound/padoru_padoru.wav
  src/main/resources/sound/sayonara_bye_bye.wav
  src/main/resources/sound/sayonara_senpai.wav
  src/main/resources/sound/sugoi_sugoi.wav
  src/main/resources/sound/tuturuu_mayushi_desu.wav
  src/main/resources/sound/waaaah.mp3
  src/main/resources/sound/waoow.mp3
  src/main/resources/waifu_alerts.json
Labels: enhancement

#164 feat: add IDE idle events
  .idea/codeStyles/Project.xml
  src/main/java/zd/zero/waifu/motivator/plugin/WaifuMotivatorProject.java
  src/main/java/zd/zero/waifu/motivator/plugin/assets/TextAssetDefinitionService.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/VisualMotivationAssetProvider.kt
  src/main/java/zd/zero/waifu/motivator/plugin/listeners/IdleEventListener.kt
  src/main/java/zd/zero/waifu/motivator/plugin/motivation/BaseMotivation.kt
  src/main/java/zd/zero/waifu/motivator/plugin/motivation/MotivationListener.java
  src/main/java/zd/zero/waifu/motivator/plugin/motivation/WaifuMotivation.java
  src/main/java/zd/zero/waifu/motivator/plugin/settings/PluginSettingsListener.kt
  src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorSettingsPage.form
  src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorSettingsPage.java
  src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorState.kt
Labels: feature

#169 fix: decoupling motivation text assets from plugin bundle
  .idea/codeStyles/Project.xml
  src/main/java/zd/zero/waifu/motivator/plugin/assets/AssetManager.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/AssetModels.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/TextAssetDefinitionService.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/TextAssetManager.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/TextAssetService.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/VisualMotivationAssetProvider.kt
Labels: enhancement

#165 feat: add task motivation events
  src/main/java/zd/zero/waifu/motivator/plugin/listeners/TaskListener.kt
  src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorSettingsPage.form
  src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorSettingsPage.java
  src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorState.kt
  src/main/resources/META-INF/plugin.xml
  src/main/resources/messages/MessageBundle.properties
Labels: feature

#170 feat: enable more visual event categories for Motivate Me action
  src/main/java/zd/zero/waifu/motivator/plugin/actions/MotivateMeAction.java
  src/main/java/zd/zero/waifu/motivator/plugin/alert/BaseWaifuNotification.kt
  src/main/java/zd/zero/waifu/motivator/plugin/alert/NonTitledVisualNotification.kt
  src/main/java/zd/zero/waifu/motivator/plugin/alert/VisualWaifuNotification.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/VisualMotivationAssetProvider.kt
  src/main/java/zd/zero/waifu/motivator/plugin/motivation/VisualMotivationFactory.kt
Labels: feature

#171 chore: bump pre-merge pipeline JRE to 11
  .github/workflows/pre-merge.yml
Labels: chore

#177 chore: back to using filename utils
  src/main/java/zd/zero/waifu/motivator/plugin/player/WaifuSoundPlayerFactory.java
Labels: chore

#179 fix: enable plugin actions during indexing
  src/main/java/zd/zero/waifu/motivator/plugin/actions/MotivateMeAction.java
  src/main/java/zd/zero/waifu/motivator/plugin/actions/PluginSettingsAction.java
  src/main/java/zd/zero/waifu/motivator/plugin/actions/ShowWaifuOfTheDayAction.java
Labels: enhancement, status: review-in-progress

#173 feat: Offline Mode
  build.gradle
  src/main/java/zd/zero/waifu/motivator/plugin/ProjectConstants.kt
  src/main/java/zd/zero/waifu/motivator/plugin/WaifuMotivatorProject.java
  src/main/java/zd/zero/waifu/motivator/plugin/actions/MotivateMeAction.java
  src/main/java/zd/zero/waifu/motivator/plugin/assets/AssetManager.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/AssetModels.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/AudibleAssetDefinitionService.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/AudibleAssetManager.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetDefinitionService.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetManager.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/TextAssetDefinitionService.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/TextAssetManager.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/TextAssetService.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/VisualAssetDefinitionService.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/VisualAssetManager.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/VisualMotivationAssetProvider.kt
  src/main/java/zd/zero/waifu/motivator/plugin/integrations/ErrorReporter.kt
  src/main/java/zd/zero/waifu/motivator/plugin/listeners/IdleEventListener.kt
  src/main/java/zd/zero/waifu/motivator/plugin/listeners/TaskListener.kt
  src/main/java/zd/zero/waifu/motivator/plugin/listeners/WaifuUnitTesterListenerImpl.kt
  src/main/java/zd/zero/waifu/motivator/plugin/onboarding/UpdateNotification.kt
  src/main/java/zd/zero/waifu/motivator/plugin/tools/AssetTools.kt
  src/main/java/zd/zero/waifu/motivator/plugin/tools/ExceptionTools.kt
  src/main/java/zd/zero/waifu/motivator/plugin/tools/Extensions.kt
  src/main/java/zd/zero/waifu/motivator/plugin/tools/RestClient.kt
  src/main/java/zd/zero/waifu/motivator/plugin/tools/ToolBox.kt
  src/test/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetDefinitionServiceTest.kt
  src/test/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetManagerTest.kt
  src/test/java/zd/zero/waifu/motivator/plugin/assets/TextAssetServiceTest.kt
  src/test/java/zd/zero/waifu/motivator/plugin/assets/VisualMotivationAssetProviderTest.kt
  src/test/java/zd/zero/waifu/motivator/plugin/test/tools/TestTools.kt
  src/test/java/zd/zero/waifu/motivator/plugin/tools/ToolBoxKtTest.kt
  src/test/resources/text/assets.json
  src/test/resources/text/empty.json
  src/test/resources/text/facts.txt
  src/test/resources/text/shocked.json
  src/test/resources/visuals/assets.json
  src/test/resources/visuals/hard-to-swallow-pills.txt
  src/test/resources/visuals/waiting/konata_bored_one.gif
  src/test/resources/visuals/waiting/ryuko_waiting.gif
Labels: feature

#181 fix: prevent multiple idle events
  src/main/java/zd/zero/waifu/motivator/plugin/WaifuMotivatorProject.java
  src/main/java/zd/zero/waifu/motivator/plugin/listeners/IdleEventListener.kt
Labels: bug, status: review-in-progress

#175 chore: update asset metadata on version upgrade
  src/main/java/zd/zero/waifu/motivator/plugin/WaifuMotivatorProject.java
  src/main/java/zd/zero/waifu/motivator/plugin/assets/AssetManager.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetManager.kt
  src/main/java/zd/zero/waifu/motivator/plugin/onboarding/UserOnboarding.kt
  src/main/java/zd/zero/waifu/motivator/plugin/platform/LifeCycleManager.kt
  src/main/java/zd/zero/waifu/motivator/plugin/platform/UpdateListener.kt
  src/test/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetManagerTest.kt
  src/test/resources/visuals/celebration/caramelldansen.gif
  src/test/resources/visuals/updated-assets.json
Labels: chore
