Repository waifu-motivator/waifu-motivator-plugin, pull requests merged in 2020-10, with the labels that each got.

#227 fix: waifu of the day does not show up on fresh install
  src/main/java/zd/zero/waifu/motivator/plugin/WaifuMotivatorProject.java
  src/main/java/zd/zero/waifu/motivator/plugin/WaifuOfTheDayStartupActivity.java
  src/main/java/zd/zero/waifu/motivator/plugin/WaifuOfTheDayStartupActivity.kt
  src/main/java/zd/zero/waifu/motivator/plugin/alert/dialog/DialogTipPanel.java
  src/main/java/zd/zero/waifu/motivator/plugin/alert/dialog/WaifuOfTheDayDialog.java
Labels: type: enhancement

#228 fix: use temporary disposable parent
  src/main/java/zd/zero/waifu/motivator/plugin/WaifuOfTheDayStartupActivity.kt
Labels: type: enhancement

#232 fix: multi-thread safe asset check serialization
  build.gradle
  src/main/java/zd/zero/waifu/motivator/plugin/assets/LocalAssetService.kt
Labels: type: bug

#233 feat: able to group motivation assets
  src/main/java/zd/zero/waifu/motivator/plugin/WaifuMotivatorProject.java
  src/main/java/zd/zero/waifu/motivator/plugin/actions/MotivateMeAction.java
  src/main/java/zd/zero/waifu/motivator/plugin/actions/MotivateMeAction.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/AssetModels.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/AudibleAssetManager.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetDefinitionService.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/TextAssetManager.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/TextAssetService.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/VisualMotivationAssetProvider.kt
  src/main/java/zd/zero/waifu/motivator/plugin/motivation/MotivationFactory.kt
  src/main/java/zd/zero/waifu/motivator/plugin/motivation/MotivationLifecycleListener.kt
  src/main/java/zd/zero/waifu/motivator/plugin/motivation/VisualMotivationFactory.kt
  src/main/java/zd/zero/waifu/motivator/plugin/motivation/event/MotivationEvents.kt
  src/main/java/zd/zero/waifu/motivator/plugin/personality/Wendi.kt
  src/main/java/zd/zero/waifu/motivator/plugin/personality/core/IdlePersonalityCore.kt
  src/main/java/zd/zero/waifu/motivator/plugin/personality/core/TaskPersonalityCore.kt
  src/main/java/zd/zero/waifu/motivator/plugin/tools/AssetTools.kt
  src/main/java/zd/zero/waifu/motivator/plugin/tools/ToolBox.kt
  src/test/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetDefinitionServiceTest.kt
  src/test/java/zd/zero/waifu/motivator/plugin/assets/TextAssetServiceTest.kt
  src/test/java/zd/zero/waifu/motivator/plugin/assets/VisualMotivationAssetProviderTest.kt
  src/test/resources/text/shocked.json
Labels: type: feature

#237 feat: able to set preferred characters
  src/main/java/zd/zero/waifu/motivator/plugin/assets/AssetModels.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetDefinitionService.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetManager.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/VisualAssetManager.kt
  src/main/java/zd/zero/waifu/motivator/plugin/service/WaifuGatekeeper.kt
  src/main/java/zd/zero/waifu/motivator/plugin/settings/CheckboxListUI.kt
  src/main/java/zd/zero/waifu/motivator/plugin/settings/SettingsTools.kt
  src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorSettingsPage.form
  src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorSettingsPage.java
  src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorState.kt
  src/main/resources/META-INF/plugin.xml
  src/main/resources/messages/MessageBundle.properties
  src/test/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetDefinitionServiceTest.kt
  src/test/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetManagerTest.kt
Labels: type: feature

#240 feat: added frustration cool down
  .idea/codeStyles/Project.xml
  src/main/java/zd/zero/waifu/motivator/plugin/personality/Wendi.kt
  src/main/java/zd/zero/waifu/motivator/plugin/personality/core/emotions/CoolDownCore.kt
  src/main/java/zd/zero/waifu/motivator/plugin/personality/core/emotions/EmotionCore.kt
  src/main/java/zd/zero/waifu/motivator/plugin/personality/core/emotions/EmotionDerivationUnit.kt
  src/main/java/zd/zero/waifu/motivator/plugin/personality/core/emotions/EmotionEvents.kt
  src/main/java/zd/zero/waifu/motivator/plugin/personality/core/emotions/NegativeEmotionDerivationUnit.kt
  src/main/java/zd/zero/waifu/motivator/plugin/personality/core/emotions/NeutralEmotionDerivationUnit.kt
  src/main/java/zd/zero/waifu/motivator/plugin/personality/core/emotions/PositiveEmotionDerivationUnit.kt
  src/main/resources/META-INF/plugin.xml
  src/test/java/zd/zero/waifu/motivator/plugin/personality/NegativeEmotionCoreTests.kt
Labels: type: feature

#249 feat: Calm your Waifu down
  README.md
  gradle.properties
  src/main/java/icons/WaifuMotivatorIcons.java
  src/main/java/icons/WaifuMotivatorIcons.kt
  src/main/java/zd/zero/waifu/motivator/plugin/actions/MotivateMeAction.kt
  src/main/java/zd/zero/waifu/motivator/plugin/actions/RelaxAction.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/VisualMotivationAssetProvider.kt
  src/main/java/zd/zero/waifu/motivator/plugin/integrations/MoodStatusBarProvider.kt
  src/main/java/zd/zero/waifu/motivator/plugin/integrations/MoodStatusBarWidget.kt
  src/main/java/zd/zero/waifu/motivator/plugin/personality/Wendi.kt
  src/main/java/zd/zero/waifu/motivator/plugin/personality/core/ResetCore.kt
  src/main/java/zd/zero/waifu/motivator/plugin/personality/core/emotions/EmotionCore.kt
  src/main/java/zd/zero/waifu/motivator/plugin/personality/core/emotions/EmotionEvents.kt
  src/main/java/zd/zero/waifu/motivator/plugin/personality/core/emotions/NegativeEmotionDerivationUnit.kt
  src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorSettingsPage.form
  src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorSettingsPage.java
  src/main/java/zd/zero/waifu/motivator/plugin/settings/WaifuMotivatorState.kt
  src/main/resources/META-INF/plugin.xml
  src/main/resources/icons/emojis/1f60a.svg
  src/main/resources/icons/emojis/1f60c.svg
  src/main/resources/icons/emojis/1f60f.svg
  src/main/resources/icons/emojis/1f612.svg
  src/main/resources/icons/emojis/1f620.svg
  src/main/resources/icons/emojis/1f62d.svg
  src/main/resources/icons/emojis/1f632.svg
  src/main/resources/icons/emojis/1f642.svg
  src/main/resources/icons/emojis/1f92c.svg
  src/main/resources/icons/emojis/1f973.svg
  src/main/resources/icons/heart.svg
  src/main/resources/messages/MessageBundle.properties
  src/test/java/zd/zero/waifu/motivator/plugin/personality/NegativeEmotionCoreTests.kt
Labels: status: review-in-progress, type: feature

#253 chore: Upgrading to Kotlin 1.4 features
  src/main/java/zd/zero/waifu/motivator/plugin/alert/WaifuNotification.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetManager.kt
  src/main/java/zd/zero/waifu/motivator/plugin/integrations/MoodStatusBarWidget.kt
  src/main/java/zd/zero/waifu/motivator/plugin/listeners/ExitCodeListener.kt
  src/main/java/zd/zero/waifu/motivator/plugin/listeners/IdleEventListener.kt
  src/main/java/zd/zero/waifu/motivator/plugin/motivation/MotivationFactory.kt
  src/main/java/zd/zero/waifu/motivator/plugin/motivation/MotivationListener.kt
  src/main/java/zd/zero/waifu/motivator/plugin/motivation/event/MotivationEventListener.kt
  src/main/java/zd/zero/waifu/motivator/plugin/personality/Wendi.kt
  src/main/java/zd/zero/waifu/motivator/plugin/personality/core/PersonalityCore.kt
  src/main/java/zd/zero/waifu/motivator/plugin/personality/core/emotions/EmotionCore.kt
  src/main/java/zd/zero/waifu/motivator/plugin/personality/core/emotions/EmotionEvents.kt
  src/main/java/zd/zero/waifu/motivator/plugin/personality/core/emotions/PositiveEmotionDerivationUnit.kt
  src/main/java/zd/zero/waifu/motivator/plugin/platform/UpdateAssetsListener.kt
  src/main/java/zd/zero/waifu/motivator/plugin/service/WaifuGatekeeper.kt
  src/main/java/zd/zero/waifu/motivator/plugin/settings/PluginSettingsListener.kt
  src/main/java/zd/zero/waifu/motivator/plugin/tools/Debouncer.kt
Labels: type: chore

#255 fix: quieter sound playback error handling
  .idea/waifu-motivator-plugin.iml
  src/main/java/zd/zero/waifu/motivator/plugin/player/DefaultWaifuSoundPlayer.java
  src/main/java/zd/zero/waifu/motivator/plugin/player/Mp3WaifuSoundPlayer.java
Labels: type: bug

#257 fix: handling malformed definitions better
  src/main/java/zd/zero/waifu/motivator/plugin/assets/AssetModels.kt
  src/main/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetManager.kt
  src/test/java/zd/zero/waifu/motivator/plugin/assets/RemoteAssetDefinitionServiceTest.kt
  src/test/resources/visuals/assets.json
  src/test/resources/visuals/updated-assets.json
Labels: type: bug

#243 chore: enhance exception reporting metadata
  src/main/java/zd/zero/waifu/motivator/plugin/integrations/ErrorReporter.kt
Labels: status: feedback-provided, type: chore
